Document: detective-agency
Title: Debian detective-agency Manual
Author: <insert document author here>
Abstract: This manual describes what detective-agency is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/detective-agency/detective-agency.sgml.gz

Format: postscript
Files: /usr/share/doc/detective-agency/detective-agency.ps.gz

Format: text
Files: /usr/share/doc/detective-agency/detective-agency.text.gz

Format: HTML
Index: /usr/share/doc/detective-agency/html/index.html
Files: /usr/share/doc/detective-agency/html/*.html
